import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<nav>
					<h1>RootLayout (app/layout.tsx)</h1>
				</nav>
				{children}
			</body>
		</html>
	);
}

/*
RootLayout 컴포넌트에 적용하는 모든 항목은 다른 모든 페이지들에도 표시된다.
따라서 전역으로 적용할 속성이나 스타일을 여기에 추가하면 된다.
*/
